### ISSUE TITLE
Remove parent issue

### ISSUE THREAD

**Issue by DanilinEgor** [taskadapter/redmine-java-api#117]
I want to remove parent issue1 for some other issue2. I write:
<b>issue2.setParentId(null);
mgr.update(issue2);</b>
but it doesn't work, issue1 is still a parent of issue2! Is it a bug or I am doing something wrong?

**Comment by alexeyOnGitHub** [comment]
this is addressed in a recent commit - see the previous automatically generated comment. please try 
https://github.com/taskadapter/redmine-java-api/tree/ask-61-save-nulls-if-set branch . I added an integration test for this specific scenario (removing parent Id)

**Comment by alexeyOnGitHub** [comment]
the change was merged to "master".
