### ISSUE TITLE
support impersonating users (patch)

### ISSUE THREAD

**Issue by ConradWood** [taskadapter/redmine-java-api#120]
This adds support for redmines' ability to impersonate a user. This is useful if comments are added via an API so that they appear to be coming from a real user rather than the API.
it adds setImpersonateUser(loginname) to redmineManager. setting it to null disables the feature.
applies cleanly to current HEAD

diff --git a/src/main/java/com/taskadapter/redmineapi/RedmineManager.java b/src/main/java/com/taskadapter/redmineapi/RedmineManager.java
index 7a9bb50..5e0787a 100644
--- a/src/main/java/com/taskadapter/redmineapi/RedmineManager.java
+++ b/src/main/java/com/taskadapter/redmineapi/RedmineManager.java
@@ -132,6 +132,11 @@ public class RedmineManager {
                transport.setCredentials(login, password);
        }
 
+    public void setImpersonateUser(String username) {
+        transport.setImpersonateUser(username);
+    }
+
+
     /**
      * Sample usage:
      * <p/>
diff --git a/src/main/java/com/taskadapter/redmineapi/internal/Transport.java b/src/main/java/com/taskadapter/redmineapi/internal/Transport.
index 8da6fe2..f15cc60 100644
--- a/src/main/java/com/taskadapter/redmineapi/internal/Transport.java
+++ b/src/main/java/com/taskadapter/redmineapi/internal/Transport.java
@@ -75,6 +75,7 @@ public final class Transport {
        private final Communicator<BasicHttpResponse> errorCheckingCommunicator;
        private final BaseCommunicator baseCommunicator;
        private final RedmineAuthenticator<HttpResponse> authenticator;
+        private String impersonateUser = null;
 
   static {
                OBJECT_CONFIGS.put(
@@ -242,7 +243,10 @@ public final class Transport {
                final URI uri = getURIConfigurator().getObjectURI(obj.getClass(),
                                Integer.toString(obj.getId()));
                final HttpPut http = new HttpPut(uri);
-
+                if (getImpersonateUser() != null) {
+                   http.addHeader("X-Redmine-Switch-User", getImpersonateUser());
+                }
+  
                final String body = RedmineJSONBuilder.toSimpleJSON(
                                config.singleObjectName, obj, config.writer);
                setEntity(http, body);
@@ -581,6 +585,19 @@ public final class Transport {
        public void setLogin(String login) {
                setCredentials(login, password);
        }
+        /**
+         * @return the impersonateUser
+         */
+        public String getImpersonateUser() {
+           return impersonateUser;
+        }
+
+        /**
+        * @param impersonateUser the impersonateUser to set
+        */
+        public void setImpersonateUser(String impersonateUser) {
+           this.impersonateUser = impersonateUser;
+        }
 
        /**
         * Entity config.

**Comment by alexeyOnGitHub** [comment]
the pull request has some unresolved issues - see my comments there

**Comment by ConradWood** [comment]
I have added the impersonate user feature to other http requests as
well.

**Comment by alexeyOnGitHub** [comment]
I merged pull request https://github.com/taskadapter/redmine-java-api/pull/172 into master.
