### ISSUE TITLE
Downloading attachments not possible when connected via API access key

### ISSUE THREAD

**Issue by ZenitK** [taskadapter/redmine-java-api#121]
When calling the following constructor RedmineManager(String host, String apiAccessKey), the downloadAttachment(...) returns only the redmine html login page because the Transport doesn't contain the needed credentials.

With login and password works as expected.

**Comment by keritaf** [comment]
Should we really build content URL ourselves? As I see it, we can add API key to the URL if the key is specified. I propose PR #202 as a fix.

**Comment by alexeyOnGitHub** [comment]
nobody worked on this in the recent times, so let's move out of the current release again.
please let me know if you want to create a proper fix for this issue with tests and all.
