### ISSUE TITLE
The story_points attribute is not available for an issue

### ISSUE THREAD

**Issue by johannkohler** [taskadapter/redmine-java-api#160]
The attribute story_points that is provided by the API is not available with the java client. Is it possible to add it?

Thanks, Johann

**Comment by alexeyOnGitHub** [comment]
I verified that neither Redmine 2.5.2 not 2.6.0 have this field. this is something you got from using some 3rd party plugin.

**Comment by johannkohler** [comment]
Sorry for the delay... You have completely right, this information is provided by a plugin.
So, sorry again for the bad issue.
Cheers, Johann
