### ISSUE TITLE
How to receive issue history?

### ISSUE THREAD

**Issue by a11n** [taskadapter/redmine-java-api#179]
Hi,

the default Redmine issue details page contains a history section containing all changes done to a certain issue.

What is the redmine-java-api equivalent to receive this history?
I tried Issue's getChangeset(), getJournal() and IssueManager's getTimeEntriesById(), but those seem to return something else.

Thanks in advance,
André

**Comment by alexeyOnGitHub** [comment]
Issue Journal entries should do the trick.
What do you receive when you ask for journals? Is there something missing there?

**Comment by a11n** [comment]
Many thanks for your reply. Unfortunately `getJournals()`always returns an empty (size == 0) list although the issue has several history entries (I can see using the website).

I am using library version 2.1.0 and server:
```
Environment:
  Redmine version                2.5.1.stable
  Ruby version                   1.9.2-p0 (2010-08-18) [x86_64-linux]
  Rails version                  3.2.17
  Environment                    production
  Database adapter               Mysql2
```

**Comment by alexeyOnGitHub** [comment]
please use this:
    Issue issue = issueManager.getIssueById(id, Include.journals);

I updated Javadoc for getJournals() method to make it clear that you need to request fields explicitly.

**Comment by a11n** [comment]
Thank you very much, that solved my problem :-)
