### ISSUE TITLE
Bad date value JSONException when using Redmine 3.0.0.stable

### ISSUE THREAD

**Issue by a11n** [taskadapter/redmine-java-api#180]
I am running a Redmine server on **OS X 10.10** with the following specification:
```
Environment:
  Redmine version                3.0.0.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-darwin10.0.0]
  Rails version                  4.2.0
  Environment                    production
  Database adapter               Mysql2                
Redmine plugins:
  no plugin installed
```
(It's basically [this stack from bitnami](https://bitnami.com/redirect/to/50828/bitnami-redmine-3.0.0-0-osx-x86_64-installer.dmg))

However, I am facing this exception (com.taskadapter:redmine-java-api:2.1.0):
```
com.taskadapter.redmineapi.RedmineFormatException: org.json.JSONException: Bad date value 2015-03-09T17:41:16.000GMT-00:00
	at com.taskadapter.redmineapi.internal.Transport.parseResponse(Transport.java:563)
	at com.taskadapter.redmineapi.internal.Transport.getCurrentUser(Transport.java:198)
	at com.taskadapter.redmineapi.UserManager.getCurrentUser(UserManager.java:22)
```

I have seen that there was a similar issue in the past, but this was considered as resolved.

Maybe my server is misconfigured?! Or is it an issue with the API for Redmine versions > 3?

**Comment by alexeyOnGitHub** [comment]
This will probably be fixed by pull equestrian #175

**Comment by a11n** [comment]
Oups, my bad. Only checked the issues if this problem is known. O:-)

Anyways, it would be interesting to know if this is a general problem with this library and Redmine versions > 3.0 or if it only occurs in conjunction with the bitnami stack, which will of course also affect every software depending on this library.

**Comment by alexeyOnGitHub** [comment]
my guess is that it affects all Redmine 3.x versions.

**Comment by alexeyOnGitHub** [comment]
I submitted a feature request to Redmine developers: 
http://www.redmine.org/issues/19354  expose all date formats used by Redmine REST API

**Comment by a11n** [comment]
One slight update, I installed Redmine 2.6.2.stable and don't encounter aforementioned behavior. So I also think it's related to Redmine 3.x. I'll watch #180 to see what Redmine answers. I`ll close this ticket.
