### ISSUE TITLE
Possibility for ProjectManager.getProjectById() and MembershipManager.getMemberships(int projectId)?

### ISSUE THREAD

**Issue by a11n** [taskadapter/redmine-java-api#184]
Does the Redmine REST API allow to query for project and memberships by id at all?

Currently the Redmine Java API only supports to query by project key.

This is somehow inconvenient when working with issues, since `Issue.getProject()` only returns an instance of Project with **does not** have an identifier (=key).

In order to receive Projects and Memberships for an Issue one need to fetch all projects and iterate over this list until one instance equals to the given id only to receive the required key.

If it's possible it would be convenient to have ProjectManager and MembershipManager working with the project ID as well.

**Comment by alexeyOnGitHub** [comment]
good point. thank you for bringing this up.
I added getProjectById() method (and corresponding tests):

https://github.com/taskadapter/redmine-java-api/commit/507649fee9fc7c53a6260136e9c3417eac40f307

**Comment by alexeyOnGitHub** [comment]
also added method for memberships:
    List<Membership> getMemberships(int projectId)

https://github.com/taskadapter/redmine-java-api/commit/3b6fe7a3eb963591304427ed8e4e975dcda0b04f

can you please verify this works for you?

**Comment by a11n** [comment]
Wow, that was fast :-) Thank you very much.

With "verify this works" do you mean to test the code OR if the approach is sufficient? If you refer to the second, yes, this is absolutely what I was looking for.

Btw, are there any SNAPSHOTS available on central repo? Can't wait for the 2.1.1 release :-D

**Comment by alexeyOnGitHub** [comment]
ok, let me just release a new version. since it has some new functionality, I will rename it to 2.2.0.

**Comment by alexeyOnGitHub** [comment]
we do not publics snapshots. I pushed version 2.2.0 to OSS Sonatype repository. It will be automatically copied/mirrored to Maven Central soon.
