### ISSUE TITLE
RedmineInternalError is derived from Error, should be derived from Exception/Runtime Exception

### ISSUE THREAD

**Issue by matthiasblaesing** [taskadapter/redmine-java-api#195]
While reviewing my error handling, I noticed, that RedmineInternalError is not derived from Exception but from Error. I think this is wrong - from the documentation for Error:

```
An {@code Error} is a subclass of {@code Throwable}
that indicates serious problems that a reasonable application
should not try to catch.
```

In this case I'm connection to a "non-redmine" url and that of course can't reply with a project list. I thought I caught it (I caught Exception), but was missing this case. To reproduce:

1. Instantiate an RedmineManager with target url https://www.google.de
2. Call getProjectManager().getProject() on it

I consider this normal usage (replace google with any valid URL, without redmine installation) should give same problem.

From my perspective, nothing in redmine-java-api should generate Throwables not derived from exception. Errors are for JVM-Fatal problem: OutOfMemoryError, StackOverflowError, that are unlikely to be recoverable.

Easiest fix: 

```
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- HEAD
+++ Modified In Working Tree
@@ -6,7 +6,7 @@
  * @author maxkar
  *
  */
-public class RedmineInternalError extends Error {
+public class RedmineInternalError extends RuntimeException {
 
     private static final long serialVersionUID = 1L;
```

**Comment by alexeyOnGitHub** [comment]
we had a similar request in Issue #125, but for whatever reason decided to not change that. fixed.
