### ISSUE TITLE
Add deleting attachments 

### ISSUE THREAD

**Issue by Abbo44** [taskadapter/redmine-java-api#198]
REST Api upgraded one year ago for add deleting attachments enhancment.
Can you add this functionality to redmine java api please ?

http://www.redmine.org/issues/14828

Thank you.

**Comment by Abbo44** [comment]
https://github.com/taskadapter/redmine-java-api/issues/106

**Comment by alexeyOnGitHub** [comment]
this is a duplicate of #106 
also, the patch you mentioned was never merged into the main Redmine codebase (as of today anyway). so it is not available in Redmine's REST API.

**Comment by alexeyOnGitHub** [comment]
I see the Redmine patch was merged 3 months ago. now we can add support to the Java library
