### ISSUE TITLE
can not save a journal in a issue

### ISSUE THREAD

**Issue by masonwu1762** [taskadapter/redmine-java-api#199]
Hi,
I try to save a journal in a issue, but fails. 
I add Journals to a issue, and then update the issue as follows:
newIssue.addJournals(journals);           
issueManager.update(newIssue);
but journals are not show in the issue history on web pages.

I am using library version 2.2.0
Redmine version             2.5.3.stable
Ruby version                   1.9.3
Environment                    production
Database adapter            Mysql2

Thanks in advance,
Mason

**Comment by alexeyOnGitHub** [comment]
Issue journals are created automatically when you update existing issues. journal entries are essentially log records for changes you make. you cannot just add log records without making actual changes. this API method is misleading and it should only be used internally by Redmine Json parser when parsing response from server. we should hide it from public
