### ISSUE TITLE
2.3.0 should have been released as 3.0.0

### ISSUE THREAD

**Issue by matthiasblaesing** [taskadapter/redmine-java-api#211]
You decided to break the API semantics by disabling automatic paging for the getIssues method:

https://github.com/taskadapter/redmine-java-api/issues/196

I still think an api break should be reflected in a bump of the major version - this was suggested in the same bug above:

https://github.com/taskadapter/redmine-java-api/issues/196#issuecomment-98587738

I suggest removing that tag and retagging as 3.0.0 (changelog and gradle config need to be adjusted to).

**Comment by alexeyOnGitHub** [comment]
not worth it IMHO. let's just release more versions

**Comment by matthiasblaesing** [comment]
Ok so the message is: the version number has no meaning - every change might break your code. Sorry to put this so negative, but everybody depending on a stable API is now screwed.

If someone made this version range selection in maven: [2.0,3.0)

In theory he has done a sane thing: Don't depend on a particular version, just expect that new version in the same range add features but are API stable. In practise he believes wrong, rebuilding his package, would render it broken.

**Comment by alexeyOnGitHub** [comment]
thank you for bringing this up, you are absolutely right!

I hear you and I like proper semantic versioning too. but on the other hand I don't want to have this inflation of major version numbers - 2,3,4,5,6.... I think this library would benefit from refactoring quite a few things... its original main use-case is pretty different from how people use it now. I was going back and forth about proper semantic versioning vs. anti-inflation policy on major numbers :)

that particular version is already in Maven Central.. but let's always use proper semantic versioning from now on.
