### ISSUE TITLE
support Issue assignement to Groups in addition to Users

### ISSUE THREAD

**Issue by matthiasblaesing** [taskadapter/redmine-java-api#213]
Redmine can be configured to allow group assignments for issues:

Configuration option: Settings -> Issue Tracking -> Allow issue assignment to groups
Request: https://github.com/redminenb/redminenb/issues/40

The API currently exposes the server send information as a User, while in fact only an ID-Name pair is present. It will be difficult to fix this without an API change (there is no detectable difference between a user assignment and a group assignment).

My current thoughts:

- create an "Assignee" interface
- make Group and User implement the Assignee interface
- change the issue to use the Assignee interface
- implement a GenericAssignee, implementing Assignee and Identifiable, holding an ID and a name
- change the parser to parse an issue server reply into an GenericAssignee
- the Writer part is already in place (it only expects an Identifiable)

**Comment by zebraitis** [comment]
+1

**Comment by alexeyOnGitHub** [comment]
assigning issues to groups is a feature with a questionable value... oh well, since redmine developers decided to complicate things and implemented that stuff, we should probably support this. ugh.
@matthiasblaesing , I like the plan you outlined. I'd implement it the same way.

**Comment by alexeyOnGitHub** [comment]
this is now in "master" branch.
