### ISSUE TITLE
Notice: Android M is dropping support for Apache HTTP Client

### ISSUE THREAD

**Issue by Harti** [taskadapter/redmine-java-api#216]
Dear project maintainers,

searching through the Android-related issues I've witnessed quite a lot of ignorance about Android OS compatibility issues on your end. I'm not going to further complain about it as whether or not you want to support app developers is completely up to you. 

My aim was to create an Android library powered by your Java API library. I targeted API Level 21 (Android 5.0), encountering crashes like
```
09-16 08:32:53.034  30293-30293/de.rbitech.apps.librarytest E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: de.rbitech.apps.librarytest, PID: 30293
    java.lang.NoSuchMethodError: No static method getSystemSocketFactory()Lorg/apache/http/conn/ssl/SSLSocketFactory; in class Lorg/apache/http/conn/ssl/SSLSocketFactory; or its super classes (declaration of 'org.apache.http.conn.ssl.SSLSocketFactory' appears in /system/framework/ext.jar)
            at com.taskadapter.redmineapi.RedmineManagerFactory.createSystemDefaultConnectionManager(RedmineManagerFactory.java:178)
            at com.taskadapter.redmineapi.RedmineManagerFactory.createDefaultTransportConfig(RedmineManagerFactory.java:273)
            at com.taskadapter.redmineapi.RedmineManagerFactory.createWithUserAuth(RedmineManagerFactory.java:122)
            at de.rbitech.libs.redmineapiwrapper.util.RedmineAPIWrapper.authenticate(RedmineAPIWrapper.java:31)
            ...
```
which really confused me until I eventually realized that the function may have been deprecated (and later dropped?) from the Apache HTTP Client API in its 4.3 version. I double checked which version you are using (4.2) and thought everything was fine, but it was not.

I kept digging and tried to instantiate the `TransportConfiguration` myself, but the `PoolingClientConnectionManager` class was nowhere to be found. I could not instantiate it using the latest stable Android Studio version (1.3.2) and I was unable to find any internet resources to assist me in doing so.
[Funnily enough I found an issue in this repository](https://github.com/taskadapter/redmine-java-api/issues/58) supposedly fixing the issue (and stating that the class doesn't exist on Android), but you guys really seem to hate Android.
You either [forget about proposed patches](https://github.com/taskadapter/redmine-java-api/issues/58#issuecomment-10267446), beat around the bush [until someone fixes it on their own](https://github.com/taskadapter/redmine-java-api/issues/49#issuecomment-15566520) or [deny things being fixed altogether](https://github.com/taskadapter/redmine-java-api/issues/8#issuecomment-6522016). 
Weirdly though, the latter implied that other Android versions (> 2.3) are still being supported, but I had no luck downgrading to versions smaller than 5.0. Maybe it used to work at some point, but I couldn't get it to work.

**Anyway**, my desperate search finally led me to the Android Developers pages stating that [Android M will be dropping support for the Apache HTTP client altogether](https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client).
People will be required to add 
```
android {
    useLibrary 'org.apache.http.legacy'
}
```
to their `app.gradle` file in order to get the old client working.
*(This did not fix my project either, just so you know)*

It's probably time for you to save other Android devs some time and be honest about your library being utterly incompatible with the Android framework. 
With the Apache HTTP Client being dropped as of API Level 23 (Android 6.0) you'll either have to look into [more generic HTTP Clients like Retrofit](http://square.github.io/retrofit/) or - easier - update your Readme.md to state you don't support Android, like, at all.

Thanks,

Harti

**Comment by alexeyOnGitHub** [comment]
the readme file in this repository does not say anything about Android.

**Comment by alexeyOnGitHub** [comment]
no one has expressed any interest in working on Android support so far. 
if someone wants to spend time on making changes to make sure it works fine in Android OS, that would be great. but it must be done with proper automated testing to ensure the end product really works.
