### ISSUE TITLE
*manager instances from RedmineManager class cannot be cached and reused when RedmineManager's instance is up for garbage collection

### ISSUE THREAD

**Issue by alexeyOnGitHub** [taskadapter/redmine-java-api#222]
here is code in UserIntegrationTest:

    @BeforeClass
    public static void oneTimeSetup() {  
        RedmineManager mgr = IntegrationTestHelper.createRedmineManager();
        userManager = mgr.getUserManager();

- an instance of RedmineManager is created and then mgr.getUserManager() result is saved.
but once this method is over, RedmineManager's "mgr" instance is up for garbage collection.
and I checked in debugger that mgr's finalize() method is invoked and it calls shutdown() on the transport.

and then later calls to userManager - for example, userManager.getCurrentUser()  fail because the transport is already shut down.

recent attempt to switch to Apache HttpClient 4.5.1 made this bug more apparent, but at the time we didn't have time to investigate this so I reverted HttpClient version upgrade.
now the root cause is clear and it seems to be not related to HttpClient.

**Comment by alexeyOnGitHub** [comment]
I think we should delete finalize() from RedmineManager and document that clients must call shutdown() themselves when they are ready.

**Comment by alexeyOnGitHub** [comment]
fixed. this required breaking API changes. see the related commit.

**Comment by brunojcm** [comment]
UserManager shouldn't keep itself a reference to RedmineManager? Or to any other needed object? This bug is very weird..

**Comment by alexeyOnGitHub** [comment]
I updated the description. hopefully it is easier to read now.
