### ISSUE TITLE
switch from Java 6 to 8

### ISSUE THREAD

**Issue by alexeyOnGitHub** [taskadapter/redmine-java-api#226]
any objections?

**Comment by alexeyOnGitHub** [comment]
switched to Java 7 for now.

**Comment by alexeyOnGitHub** [comment]
I see no objections to switching all the way to Java 8. I will just do it tonight.

**Comment by alexeyOnGitHub** [comment]
done

**Comment by matthiasblaesing** [comment]
I disagree with switching to java 8 is a good idea - many linux distributions are still on openjdk 7 (yes it is supported (redhat stepped up after oracle went on). If I'm not mistaken android is also in java7.

While I like the changes in Java 8 I won't be able to follow with my fork (I noticed the vast amount of changes when I wanted to prepare a pull request for Group assignement support). Netbeans is still build on JDK7 and this won't change until netbeans 9 will be released, so I'll try to keep the plugin on the same basis.

I also noticed, that while vast changes were done, version was not incremented indicating an incompatible change.

**Comment by alexeyOnGitHub** [comment]
we had reports of issues on Android. I cannot verify those and nobody volunteered to work on Android support, so... we essentially declared Android a loss. it may or may not work but we have no regular testing for it. it made couple people unhappy, which seemed pretty weird to me - instead of helping us, they got angry that we didn't want to support their non-standard systems for free. oh well...

incrementing major version number sounds like a good idea. we can also delete some deprecated stuff while we're at it.

I understand that some tools or old operating systems may still be on Java 7.  it is their choice.
Java 7 was EOL 6+ months ago and while some tools may still want to use it, we cannot stop and wait for them all. it can take years and years. libraries stuck on java7 are contributing to the aging world of java. 

we need to move forward.
