### ISSUE TITLE
Missing "is_private" attribute in Issue object 

### ISSUE THREAD

**Issue by fefurst** [taskadapter/redmine-java-api#236]
According to Redmine REST API documentation (at http://www.redmine.org/projects/redmine/wiki/Rest_Issues) the attribute "is_private" is not implemented in the issue object mapping.

Redmine Version 2.6.0
http://www.redmine.org/versions/81

Feature 
http://www.redmine.org/issues/10914

**Comment by alexeyOnGitHub** [comment]
added support: https://github.com/taskadapter/redmine-java-api/commit/82b8096cacb8b3c3a01d59144d49e15a57361b2c
