### ISSUE TITLE
How to get more then 100 object for getChildEntries?

### ISSUE THREAD

**Issue by MikeSam** [taskadapter/redmine-java-api#239]
We need to get all users for project (Project Memberships API), but we can't get more then 100 object. 
I can set limit setObjectsPerPage(500) and this option appears in the uri, like /projects/123/memberships.json?limit=500 (Transport.java, getChildEntries). But Redmine API ignore this limit and use default limit 100. I can't find the way to use "offset" parameter.
I suppose we need functionality with auto limit/offset implemented in getObjectsList.
Mayby there is a proper way to get more then 100 for getChildEntries?
Thanks.

**Comment by 2kote** [comment]
You setup paginations settings in redmine here http://yourhost.com/settings settings_per_page_options to 500

**Comment by alexeyOnGitHub** [comment]
right, the max elements per page is set in Redmine admin screen. this cannot be controlled from the outside through REST. 
thank you, @2kote
