### ISSUE TITLE
Update TargetVersion of a Issue

### ISSUE THREAD

**Issue by marciobarroso** [taskadapter/redmine-java-api#240]
I'm trying to update an issue, but the changes don't apply in server side:

RedmineManager redmine = RedmineManagerFactory.createWithUserAuth(REDMINE_URI, REDMINE_USERNAME, REDMINE_PASSWORD);
Issue issue = redmine.getIssueManager().getIssueById(id, new Include[]{Include.attachments, Include.journals});

Version version = redmine.getProjectManager().getVersionById(9);
issue.setTargetVersion(version);
redmine.getIssueManager().update(issue);

The lib version is: redmine-java-api-2.2.0

tks

**Comment by alexeyOnGitHub** [comment]
I brought back test for updating targetVersion in Issues

this test was marked "ignored" for a while
because Redmine did not support some functionality
around versions in REST API.
I verified this test works fine with Redmine 3.2.3


see the referenced commit with sample test code
