### ISSUE TITLE
Missing "closed_on" attribute in Issue Entity.

### ISSUE THREAD

**Issue by jenghung** [taskadapter/redmine-java-api#241]
https://www.redmine.org/issues/824

When I use redmine API for showing an issue, the XML file display the "closed_on"  element represent when the issue has been closed.
```
<created_on>2015-12-02T03:02:50Z</created_on>
<updated_on>2015-12-28T06:46:25Z</updated_on>
<closed_on>2015-12-10T08:51:16Z</closed_on>
```
But the Issue Entity missing the "closed_on" attribute.

**Comment by alexeyOnGitHub** [comment]
this is solved in https://github.com/taskadapter/redmine-java-api/commit/6ce0ab9414911930f3835729133faea897ebfc99
