### ISSUE TITLE
How can I change log level for console output?

### ISSUE THREAD

**Issue by 2kote** [taskadapter/redmine-java-api#244]
I need to hide this dubug info in consloe output:
`22:23:28.830 [main] DEBUG c.t.r.internal.comm.BaseCommunicator - GET http://example.com/issues.json?project_id=testing-projecu&include=&limit=1000&offset=0&key=any_key HTTP/1.1`

I try to append redmine.log.properties file in project, but it does not work
http://prntscr.com/apcx2i

May be some doc exists?

**Comment by alexeyOnGitHub** [comment]
hi.
this library uses SLF4J for logging. you can provide your own SLF4J binding and configure it - http://www.slf4j.org/codes.html#StaticLoggerBinder 

is this helpful?

**Comment by alexeyOnGitHub** [comment]
closing the ticket because there was no response in 29 days.
