### ISSUE TITLE
Updating an issue fails if it contains some special characters

### ISSUE THREAD

**Issue by marcusschneider** [taskadapter/redmine-java-api#248]
Updating an issue does not work if the subject or description field contains certain combinations of special characters like “ and ü (U+201C and U+00FC).

The update method issueManager.update(issue) does not throw an exception or raise a warning, but the issue is not being updated.

**Comment by matthiasblaesing** [comment]
This could be a duplicate of this:

https://github.com/redminenb/redminenb/issues/46

The issue there was a broken server configuration.
