### ISSUE TITLE
Raw access to no paging results

### ISSUE THREAD

**Issue by albfan** [taskadapter/redmine-java-api#259]
For searches without pagination, would be helpful to access directly to "total_count", "offset" and "limit"

<pre>

        ...
        ]
	"total_count": 331,
	"offset": 25,
	"limit": 25
}
</pre>

It is just add another metthod on:

https://github.com/taskadapter/redmine-java-api/blob/0d4e0c01d26f136ba75942a76b3050e89ee463d6/src/main/java/com/taskadapter/redmineapi/internal/DirectObjectsSearcher.java#L19

and read variables like:

https://github.com/taskadapter/redmine-java-api/blob/dccf43b06f35b8edadb8ee09936dc35bf1da3217/src/main/java/com/taskadapter/redmineapi/internal/Transport.java#L476

Using jitpack is easy to develop on snapshot

https://github.com/albfan/RedmineJavaCLI/blob/master/build.gradle#L35

so I could test as soon as you commit it, or I can fork and send a PR until it is done, whatever you prefer if you find interesting

**Comment by alexeyOnGitHub** [comment]
hi! I'm busy with other projects right now, so please feel free to submit a PR with tests and such. I will take a look
