### ISSUE TITLE
How to get issues by custom field value

### ISSUE THREAD

**Issue by mschuerer** [taskadapter/redmine-java-api#261]
Hi,
I tried to get issues wit a parametre map 
```
parameters.put("cf_1", "myValue");
List<Issue> issues1 = issueManager.getIssues(parameters);

```
but it allways return all issues and not only the one I expected.
Any ideas?
MAik

**Comment by alexeyOnGitHub** [comment]
hi! have you tried running this query in Postman or browser? what is the URL that you are using? let's compare it to the one built by the library.

**Comment by vvmsalat** [comment]
Hi, 
after some struggling i added the project name, then it worked for me:
`params.put("project_id","yourProjName");`

the project name  is also mentioned in the URL...
