### ISSUE TITLE
Support 'inherit_members' when creating projects

### ISSUE THREAD

**Issue by jboubechtoula** [taskadapter/redmine-java-api#262]
Hello,

Can you implement **inherit_members** option for creating project ?

Regards,
Julien B.

**Comment by alexeyOnGitHub** [comment]
clarification: I see "inherit_members" option in Redmine web UI plus it is also documented here: http://www.redmine.org/projects/redmine/wiki/Rest_Projects

let's see if anyone is willing to submit a patch for this.
