### ISSUE TITLE
Issue with Java 8 and redmine-java-api 3.0.0 : Unsupported class version

### ISSUE THREAD

**Issue by tpinkowski** [taskadapter/redmine-java-api#269]
Hi everyone,

We just faced an Issue using the Redmine Java API in a JSP, which is caused by: 

`javax.servlet.ServletException: javax.servlet.jsp.JspException: java.lang.UnsupportedClassVersionError: com/taskadapter/redmineapi/NotFoundException: Unsupported major.minor version 52.0 (unable to load class com.taskadapter.redmineapi.NotFoundException)`

The details from environment are:

Apache Tomcat 7.0.65
Redmine Java-API version: 3.0.0
java version: "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

**Comment by alexeyOnGitHub** [comment]
The error message shows that your java version is lower than 8. How did you check the java version that your server is running on?

**Comment by tpinkowski** [comment]
java -version.

Additionally i have set the JRE_HOME variable to the path of the Java 8 version.

**Comment by alexeyOnGitHub** [comment]
"java -version" command only shows what java version you have first in your search path. given that you can have multiple Java versions installed, this one may or may not be the version used by your Tomcat.

can you please check with Tomcat Manager app? http://stackoverflow.com/questions/13287502/which-java-version-does-tomcat-use

**Comment by tpinkowski** [comment]
You're right- The issue was a wrong jdk version in a run-script.

Thanks.
