### ISSUE TITLE
getNotes() always null

### ISSUE THREAD

**Issue by katzenjoggl** [taskadapter/redmine-java-api#274]
Hi,
i am trying to get all Notes from one issue:
                ...
		Issue i1 = ix.getIssuebyID(2241);
		System.out.println(i1.toString());
		System.out.println(i1.getDescription());
		System.out.println(i1.getNotes());
                ...

There are 3 Notes in this ticket. But I always get "null"...

Output:
Issue [id=2241, subject=test1]
safdasdf
**null**

I am using Redmine 3.1.6.stable

Thanks for your help

**Comment by katzenjoggl** [comment]
i am able to get all notes with the journals.
But should issue.getNotes() also work?

**Comment by alexeyOnGitHub** [comment]
see the new javadoc I just added. getNotes() has totally different meaning.
