### ISSUE TITLE
Internal servers error (HTTP500) is silently ignored

### ISSUE THREAD

**Issue by JeP42** [taskadapter/redmine-java-api#277]
For the case that an internal server error occured while processing the request, this error is silently ignored. An exception (RedmineException) would be nice in such a situation so that clients are able to implement proper error handling. 

Maybe`com.taskadapter.redmineapi.internal.comm.redmine.RedmineErrorHandler` would be the right place to implement handling for HTTP-5x responses.

**Comment by alexeyOnGitHub** [comment]
you are welcome to provide a patch for this, including tests. I would be happy to review and merge as long as coding standards are met and proper tests are included.
