### ISSUE TITLE
Fixing test suite

### ISSUE THREAD

**Issue by albfan** [taskadapter/redmine-java-api#283]
#281 and #282 fix all the test suite

In general, you need to configure your own redmine deploy to test project. Some details about testing should be added to a README or HACKING file

- You need to enable assign issues to groups
- You need to create 3 custom fields
- You need to configure api_test.properties for user, url and token
- Your user should use english as language

Maybe a property file for CI should be added and a way to launch gradle test using that file

**Comment by alexeyOnGitHub** [comment]
feel free to submit a PR with doc changes. this issue is not actionable on its own, so I will close it.
