### ISSUE TITLE
Update Issue is not working

### ISSUE THREAD

**Issue by jarbaspsf** [taskadapter/redmine-java-api#286]
I've tried to update a issue with a custom field, following the tutorial at Readme and i got no results. The same ocurr when i tried to add a Journal.

I believe that issueManager().updateIssue() is calling RedmineJSONBuilder.toSimpleJSON with a wrong writter perhaps?

**Comment by alexeyOnGitHub** [comment]
cannot proceed on this request without code sample and stacktrace or specific bug info.
feel free to reopen once that is provided, also please provide a patch/ Pull Requests with a fix and proper tests. I would be happy to review and merge that
