### ISSUE TITLE
Examples or documentation for SSL/TLS issues missing

### ISSUE THREAD

**Issue by dpalic** [taskadapter/redmine-java-api#292]
Is there any chance to provide us a example of how to use a SSL certificate, which is not officially supported by a CA certificate in the JVM?

I could sadly not find any hint neither in Readme.MD nor, wiki nor in example code.

**Comment by dpalic** [comment]
I have started a doc to contribute here: https://github.com/taskadapter/redmine-java-api/wiki/HowToUseSelfSignedCertificates
Hope I have got the point of how to use the API regarding SSL properly

**Comment by meirka5** [comment]
Hi, i have the same issue exactly.

Please give support to this issue.

**Comment by dpalic** [comment]
really no help here?

**Comment by alexeyOnGitHub** [comment]
I added a snippet at the end of README.md file
