### ISSUE TITLE
how to get closed issues?

### ISSUE THREAD

**Issue by chenqilongwuxi** [taskadapter/redmine-java-api#293]
final Map<String, String> para = new HashMap<String, String>();
para.put("project_id", project_id);
final ResultsWrapper<Issue> resultsWrapperMain =  mgr.getIssueManager().getIssues(para);

can't get closed issue.

**Comment by Yoshiiix** [comment]
Hi,
By default the status is "Open" and you have to specify in your Map.
To get all status use the value "*".

para.put("status_id", "*");

**Comment by alexeyOnGitHub** [comment]
@Yoshiiix thank you, I added this to README file
