### ISSUE TITLE
POST retrieve 412 when using HTTPS

### ISSUE THREAD

**Issue by TCM5** [taskadapter/redmine-java-api#296]
Currently I'am using the same implementation of this API in 2 different environments, with the same application server, but one is set as HTTP and the other as HTTPS. Both communicate with the same server of redmine, but when testing they have a different behaviour. In the HTTP one, all works well, users are created, view/create issues too. In the other, the HTTPS when the api makes a POST the response is allways an 412 code. The Redmine is configured to support https. This seems to be a bug

**Comment by alexeyOnGitHub** [comment]
what is the response message from the server? you can probably find some info in redmine logs on the server.
also, is your SSL cert valid?
this is something to debug while running tests against your server since tests work fine with a custom certificate for dev.taskadapter.com Redmine install

**Comment by alexeyOnGitHub** [comment]
closing the request until more info is provided. the request is not actionable as-is.
