### ISSUE TITLE
MembershipManager getMemberships doesn't get all

### ISSUE THREAD

**Issue by ceac13** [taskadapter/redmine-java-api#298]
The method getMemberships from MembershipManager just return 25 items at maximum. Probably it's caused by paging limit of Redmine API.

**Comment by akurutin** [comment]
I also noticed this and it is because of the limit of 25

**Comment by alexeyOnGitHub** [comment]
you are welcome to propose a patch for this

**Comment by alexeyOnGitHub** [comment]
RedmineManager class as `setObjectsPerPage` method that defines how many items are requested from Redmine in each request.
it is up to Redmine server whether or not it will honor this request.  I expect it to ignore  numbers  above a certain limit to protect the server.
