### ISSUE TITLE
issue.getJournals() return an empty Collection<Journal>

### ISSUE THREAD

**Issue by Benoit-Besnier** [taskadapter/redmine-java-api#301]
Here a sample :

```
RedmineManager redmine = RedmineManagerFactory.createWithApiKey(rmUri , rmAccessKey);
final Map<String, String> params = new HashMap<>();
Collection<Journal> journals;

params.put("issue_id", "107263"); // 107263 can be replaced by any valid issue id
params.put("include", "journals");

redmine.getIssueManager().getIssues(params).getResults();

for (Issue issue : issues) {
    journals = issue.getJournals(); // journals.size() = 0 but should be equal to 11 :(
   // ...
}
```

Any idea about this result ? Did I do something wrong with getIssues() ?

**Comment by jpthomasset** [comment]
It seems you can only get journals when using getIssueById. It seems to be a limitation of the redmine rest api:
see [Redmine Issues API](http://www.redmine.org/projects/redmine/wiki/Rest_Issues) & [Redmine Issues by id API](http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Showing-an-issue).

**Comment by Benoit-Besnier** [comment]
You're right, thank you for your answer.
