### ISSUE TITLE
No static method getSystemSocketFactory()Lorg/apache/http/conn/ssl/SSLSocketFactory;

### ISSUE THREAD

**Issue by yanwenruigithub** [taskadapter/redmine-java-api#303]
I used redmine but in creating the RedmineManager times this error, I thought it was the class conflict with the SDK, but after resolving the conflict, it was still wrong, what should I do?

**Comment by alexeyOnGitHub** [comment]
this means incompatibility with Apache HttpClient you are using. please check the required  version in this project's build.gradle file and try that one in your project.
