### ISSUE TITLE
Custom queries management

### ISSUE THREAD

**Issue by lpavone** [taskadapter/redmine-java-api#304]
Hi all, sorry if this is a silly question but I haven't figured out if it is possible to create and save custom queries with filters. Am I wrong or am I missing something?
I've seen the SavedQueryFactory allows creation but only passing an integer as parameter, so it seems to me this feature is not supported. Also, SavedQuery object does not accept any filters.
I would like to create custom queries using filters like status or assignee.
I'm already using the API which is awesome, simplified to me the management and saves time. 
Thanks in advance.

**Comment by alexeyOnGitHub** [comment]
I am closing this until someone decides to check and implement this
