### ISSUE TITLE
Get Users from group

### ISSUE THREAD

**Issue by cudu** [taskadapter/redmine-java-api#310]
How do I get users from a group?

**Comment by javiertuya** [comment]
Redmine api allows some optional filters on status, name and group_id, see http://www.redmine.org/projects/redmine/wiki/Rest_Users

This retrieves users by name using the redmine-java-api (given` userName`):

```
final Map<String,String> params = new HashMap<>();
params.put("name", userName);
final ResultsWrapper<User> users = mgr.getUserManager().getUsers(params);
```
If params are set as `params.put("group_id", groupId)`, it should retrieve the users that belong to `groupId`.

**Comment by cudu** [comment]
thanx alote, helped me.
