### ISSUE TITLE
issue could not add watchers

### ISSUE THREAD

**Issue by rongbo** [taskadapter/redmine-java-api#317]
Why was it that after I added watchers to issue, the actual issue was created successfully, but no watchers was found?In version 1.25

**Comment by javiertuya** [comment]
Yo may try current version 3.1.2. There have been many improvements since 1.25, some of them related to watchers

**Comment by alexeyOnGitHub** [comment]
closing this issue, there is no point in supporting version 1.25. feel free to reopen it and submit a PR with a fix if the issue is still reproducible with the current version
