### ISSUE TITLE
Unable to obtain list of users to add as assignee to a new Issue. 

### ISSUE THREAD

**Issue by prakharrke** [taskadapter/redmine-java-api#322]
How do I get list of users to give my users a choice to set an assignee to a new Issue?
I tried using getUsers() but it gives me FORBIDDEN. 
As I understand, it is because current logged in user does not have access to user list.
But if I use the same credentials to log in to my redmine through redmine UI, I can see the list of users, as well as a list of users while creating new issue in Assignee dropdown.

**Comment by javiertuya** [comment]
You can call `GET /projects/:project_id/memberships.json` to get all memberships: https://www.redmine.org/projects/redmine/wiki/Rest_Memberships

**Comment by alexeyOnGitHub** [comment]
"get users" operation requires Admin permissions in Redmine. feel free to ping Redmine dev team to remove this restriction, I submitted a ticket about this ~5+ years ago :)
