### ISSUE TITLE
Error 404 in User.getCurrentUser()

### ISSUE THREAD

**Issue by emiliogq** [taskadapter/redmine-java-api#327]
Hi,

I need this method but when I tried it in a Test java class it throws me a Not found exception:

``
import com.taskadapter.redmineapi.RedmineException;
import com.taskadapter.redmineapi.RedmineManager;
import com.taskadapter.redmineapi.RedmineManagerFactory;
import com.taskadapter.redmineapi.UserManager;

public class Test {

	public static void main(String[] args) {
		RedmineManager mgr = RedmineManagerFactory.createWithUserAuth("https://redmine.ice.csic.es", "privateuser","password");
		UserManager umgr = mgr.getUserManager();
		
		try {
			umgr.getCurrentUser();
		} catch (RedmineException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
``
com.taskadapter.redmineapi.NotFoundException: Server returned '404 not found'. response body:<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Redmine 404 error</title>
  <style>
    body {font-family: "Trebuchet MS", Georgia, "Times New Roman", serif; color: #303030; margin: 10px;}
    h1 {font-size:1.5em;}
    p {font-size:0.8em;}
  </style>
</head>
<body>
  <h1>Page not found</h1>
  <p>The page you were trying to access doesn't exist or has been removed.</p>
  <p><a href="javascript:history.back()">Back</a></p>
</body>
</html>

The redmine version is 3.4.6

What's wrong?

Thanks in advance

**Comment by emiliogq** [comment]
It was caused by the missing last slash. The error message could be more specific.

**Comment by alexeyOnGitHub** [comment]
if a Redmine server responds with "404 - not found", the library cannot reliably detect if this is due to some items not found by the REST API, or the URL itself is not valid. there could be all kinds of web servers sitting in front of Redmine, and they can return arbitrary text .
feel free to submit a PR with some docs / code samples if you think some URLs are not valid in sample code.
