### ISSUE TITLE
Can't set AuthorId

### ISSUE THREAD

**Issue by blazenn12** [taskadapter/redmine-java-api#329]
Hi, i want to create issues with various AuthorId. But every created issue is posted by my redmine manager. 

```
RedmineManager  redmineManager = RedmineManagerFactory.createWithApiKey("myRedmineUri", "myApiAcessKey");

Issue issue = new Issue(redmineManager .getTransport(), projectId)
        .setSubject("testSubject")
        .setDescription("testDescription")
        .setAuthorId(5);
        .create();
```

Pls, tell me whats wrong?

**Comment by alexeyOnGitHub** [comment]
according to this page https://www.redmine.org/projects/redmine/wiki/Rest_Issues#Creating-an-issue  , Redmine REST API ignores this parameter. 
I will update javadoc on `Issue` class
