### ISSUE TITLE
Request timeout?

### ISSUE THREAD

**Issue by Sir-Will** [taskadapter/redmine-java-api#332]
What would be the best way to add a timeout when the redmine site is not reachable?
This api doesn't seem to have a implementation of timeout.

**Comment by alexeyOnGitHub** [comment]
timeouts are outside of the scope of this library because they are typically handled by http client layer.
you can set timeouts when creating an instance of HttpClient before providing it to the library:

```
    public static RedmineManager createWithApiKey(String uri,
                                                  String apiAccessKey, HttpClient httpClient) {
        return new RedmineManager(new Transport(new URIConfigurator(uri,
                apiAccessKey), httpClient));
    }


```
