### ISSUE TITLE
Update redmine versions compatibility on wiki

### ISSUE THREAD

**Issue by psh-axelor** [taskadapter/redmine-java-api#343]
Hello,

Could you please update the redmine versions compatibility on wiki(https://github.com/taskadapter/redmine-java-api/wiki/Redmine-versions-compatibility)

As i checked it was last updated by Alexey on 23 Jul 2016

Thank you

**Comment by alexeyOnGitHub** [comment]
that page is not maintained anymore. not worth the effort.
