### ISSUE TITLE
Java 11 requirement

### ISSUE THREAD

**Issue by stolp** [taskadapter/redmine-java-api#353]
Today I noticed, that the 4.0.0.rc2 build is now requiring Java 11, previous versions where requiring Java 8.

What is the rationale behind this?

I think if the sources are not really suddenly requiring Java 11 language features it would be much more friendly to consuming applications to stay at Java 8.

**Comment by alexeyOnGitHub** [comment]
strictly speaking, there is no urgency to move off the old Java version(s). Java  11 and 14 do bring some improvements, and whether or not they are super useful can be debated of course, but overall I think it is reasonable to assume that the Java world will be gradually moving off end-of-life products, it is just a question of WHEN.  a major redmine library release (4.x) looks like a good place to make that change. 
Java 11 has been available for years, and even though it is also obsolete (like Java 8),  I think it is a good candidate platform for the near future. porting it to Java 14 may be pushing it a bit too much at the moment. Java 14 "records" look like an interesting addition (finally addressing one of the most common complaints about Java syntax), but that change is not production ready yet.

if someone wants to stay on the old pre-Java-11 version, they can do this, no rush to migrate. no active development is happening in this project.

**Comment by stolp** [comment]
Thanks a lot for your answer, I think we have a quite different view on obsoletion.

Which is ok, as it is a matter of different perspectives.

Personally I consider everything that is not an LTS release as not relevant, so this leaves Java 8 (supported until 2022/2030) and Java 11 (supported until 2023/2028) in the game. I think the next LTS isn't even defined yet. And yes , I find records tempting as well.

As my wish to you and all other authors of library code: Please be as defensive as possible with runtime upgrades. Not everyone is able to follow an upgrade route easily.

Maybe I'm just getting old ... :)
