### ISSUE TITLE
Location of JavaDoc

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [taskadapter/redmine-java-api#366]
Hi,  
I've seen in your README that in Maven Central there is supposed to be the documentation, however I can't find it.. can you please link it?

**Comment by AlbertoSinigaglia** [comment]
ok, never mind , [found it](https://repo1.maven.org/maven2/com/taskadapter/redmine-java-api/4.0.0.preview.3/)... but why there is not javadoc on the code itself?

**Comment by alexeyOnGitHub** [comment]
the javadoc is a part of the source code , and it is also packaged into a separate "-javadoc.jar" file and uploaded to Maven Central. not sure I understand the last question.
