### ISSUE TITLE
allow erasing values in fields

### ISSUE THREAD

**Issue by anchialas** [taskadapter/redmine-java-api#61]
Several issue fields are notn-mandatory but cannot be reset through the redmine-java-api because changes are only added to the JSON output if the value is not null. 

Affected fields are:
* Assignee
* Category
* Target Version
* Parent Issue Id
* Due Date
* Estimated time
* Description
* ...?

Sample code from RedmineJSONBuilder:
<pre>
if (issue.getAssignee() != null) {
			JsonOutput.addIfNotNull(writer, "assigned_to_id", issue
					.getAssignee().getId());
}
</pre>

**Comment by matthiasblaesing** [comment]
As the fix for setting the project went into master, I rebased the change described above onto master and added some javadoc to describe the intended usage.

**Comment by alexeyOnGitHub** [comment]
I created this: http://stackoverflow.com/questions/38335065/how-to-use-camelcase-in-idea-live-templates/38335154#38335154 for the new "is...present" boilterplate generation.

**Comment by albfan** [comment]
I think most abstraction layers face this problems in some point. Why not stick on solutions from other libraries?.

See hibernate. They flag its updates with [dynamicUpdate](http://www.mkyong.com/hibernate/hibernate-dynamic-update-attribute-example/). 

Here configuring `dynamicUpdate` as `true` by default, covers backward compatibility for this library behaviour, but opens the gate for a future change, where `dynamicUpdate` would be `false` by default.

**Comment by alexeyOnGitHub** [comment]
feel free to checkout and play around with this new branch: https://github.com/taskadapter/redmine-java-api/tree/ask-61-save-nulls-if-set
you can see the list of recent commits - I converted a bunch of classes to use "property storage" which enables tacking "not defined" vs. "explicitly set to null".

**Comment by albfan** [comment]
I will focus on this test

https://github.com/taskadapter/redmine-java-api/blob/ask-61-save-nulls-if-set/src/test/java/com/taskadapter/redmineapi/internal/RedmineJSONBuilderTest.java#L44

> public void fieldsExplicitlySetToNullAreAddedToIssueJSonAsNull()

and split it on two test: One propagate nulls and the other don't. The idea is `RedmineJSONBuilder.toSimpleJSON` receive a flag for that behaviour, avoiding add optionals on every DTO and massive usage of:

https://github.com/taskadapter/redmine-java-api/blob/ask-61-save-nulls-if-set/src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONBuilder.java#L273 

	private static void addIfSet(JSONWriter writer, String jsonKeyName, PropertyStorage storage, Property<?> property) throws JSONException {
		if (storage.isPropertySet(property)) {
			writer.key(jsonKeyName);
			writer.value(storage.get(property));
		}
	}

which seems to be hard to maintain and an extend. Even more using annotations on DTO and custom mapper code would be keeped up to date in no time

http://stackoverflow.com/a/11761975/848072

NON_NULL would be the actual behaviour and non setting that the new behaviour (storing nulls)

**Comment by alexeyOnGitHub** [comment]
hi guys. is anyone interested in trying out the current dev branch (https://github.com/taskadapter/redmine-java-api/tree/ask-61-save-nulls-if-set) and giving feedback?  

@albfan please keep in mind that the goal of this change is to distinguish between "explicitly set to null" and "not set" fields. marking fields as "not null" or using "save nulls" flag in the json mapper would not help with that. 

feel free to share your technical proposal in a PR in case I misunderstood your idea.

**Comment by alexeyOnGitHub** [comment]
the change was merged to "master".

**Comment by albfan** [comment]
You are right about explicity set to null.

**Comment by matthiasblaesing** [comment]
@alexeyOnGitHub sorry for the late reply. I was busy with other projects. Yesterday I did a first port of the redminenb project to the 3.0.0-SNAPSHOT version and most thinks worked out of the box. 

I'm not sure whether I like the fact, that the assignee, project and so on information was flattend into name/id properties on their respective parents, but I can live with that change. Some properties need further work to be unsettable and some functions need getters for the name components (Membership). I'll supply PRs for these.

**Comment by alexeyOnGitHub** [comment]
@matthiasblaesing I'm glad it almost worked for you :)
the flat structure is to support "set to null" feature as well as remove confusion on what fields are set in what circumstances. 
I agree that some properties require more changes for "send if  set" mode. I don't use many of those fields in my other project and I cannot easily verify the validity of those...
it would be great if you could find and fix them. thanks!
