### ISSUE TITLE
Problems uploading large attachements - allow to specify content length to work around the bug in redmine installs

### ISSUE THREAD

**Issue by titonio** [taskadapter/redmine-java-api#78]
Redmine 2.0.1
latest redmine-java-api
-------------------------------------------

When we try to upload an attachement file with a considerable size (50kb for example) (lower then the accepted by redmine) the file is sent in chunks, the redmine answers with 201 OK but with a malformed token which invalidates its reference on an issue.

Workaround: In the Transport class in the method
public String upload(InputStream content)

if you specify the correct size instead of -1 in the inputstream this works correctly.

**Comment by alexeyOnGitHub** [comment]
I see some simple solutions for upload, e.g.: https://github.com/kkapron/redmine-java-api/commit/c5239db382ef2562456cdca1fbb3094a9628ef94

**Comment by alexeyOnGitHub** [comment]
completed.
